- name: Deploy Calculator App

  hosts: local

  tasks:
    - name: Remove old containers #remove old container if exists
      docker_container:
        name: calculator
        state: absent
        force_kill: yes

    - name: Deploy Calculator App
      # run in background & interactive
      docker_container:
        name: sci-calc
        image: siddeshwarsk/scientific-calculator:latest
        state: started
        interactive: yes
        detach: yes